name: test

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Tokyo

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'package.json'
          package-manager-cache: false
      # バージョンはpackage.jsonのdevEngines.packageManagerから読まれる
      - uses: pnpm/action-setup@ff378ebe6b225b0680b81c1ad4498ae0d1d3a5e3 # v6.0.10
      - uses: openameba/action-npm-cache/restore@af6e98076ee69d0eb6f0b6550233164833822142 # v1.2.1
      - run: pnpm test
      - if: github.ref_name == 'main'
        uses: openameba/action-npm-cache/save@af6e98076ee69d0eb6f0b6550233164833822142 # v1.2.1
